name: CI Pipeline - Job Resume Matcher

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # --- Backend Setup ---
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          cd ai-service
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- Frontend Setup ---
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # --- Store Build Artifacts ---
      - name: Upload frontend build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build

      - name: Upload backend build
        uses: actions/upload-artifact@v4
        with:
          name: backend-service
          path: ai-service
